apiVersion: v1
kind: Service
metadata:
  name: {{ include "inlets.fullname" . }}
  labels:
    {{- include "inlets.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      name: data
      port: 8000
  selector:
    {{- include "inlets.selectorLabels" . | nindent 4 }}
